### PR TITLE
add start_debug_demo.launch,

### PR DESCRIPTION
**Pull request by k-okada**
http://wiki.ros.org/tf/Tutorials/Debugging%20tf%20problems using start_debug_demo.launch, but it is not find in this pakcage, add launch file and c++ program that users can follow the tutorial.

We also need to correct tutorial, because it seems error massage have been updated

c.f. http://wiki.ros.org/tf/Tutorials/Debugging%20tf%20problems

### CODE REVIEW

**Comment by shokoofeh** [comment]
The launch file and cpp program can also be added to the content of the [Debugging tf tutorial](http://wiki.ros.org/tf/Tutorials/Debugging%20tf%20problems) so that users can add (and modify) them to the "learning_tf" package which is created in the learning process of the [Learning tf tutorial](http://wiki.ros.org/tf/Tutorials#Learning_tf).

**Comment by k-okada** [comment]
@Shokoofeh thanks for comment, Do you mean that we should update the tutorial? 
As far as I understand, In the tutorial (http://wiki.ros.org/tf/Tutorials/Debugging%20tf%20problems ) it assumes there are start_debug_demo.launch in the turtle_tf package, but it is not located on the https://github.com/ros/geometry_tutorials/tree/hydro-devel/turtle_tf/launch. That's the problem and I added the file to match the tutorial.

**Comment by shokoofeh** [comment]
Yes. I think in addition to include these files to the main repo, we can add them to the tutorial too. Like [this](http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20listener%20%28C%2B%2B%29#The_Code) part of [Writing a listener tutorial](http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20listener%20%28C%2B%2B%29).

**Comment by k-okada** [comment]
I see, I think I understand you suggestion. see 
http://wiki.ros.org/tf/Tutorials/Debugging%20tf%20problems#preview for updates

**Comment by 130s** [comment]
+1. @wjwwood

**Comment by tfoote** [comment]
Thanks for the pull-request.

**Comment by 130s** [comment]
@tfoote Could you cherry-pick this into other valid branches, or is it also something pull request is expected for?

**Comment by tfoote** [comment]
After more testing/fixups I plan to merge everything into indigo. I'm not planning to backport to the EOL'd distros. If you'd like things there please pull-request.

**Comment by 130s** [comment]
Got it. So is new release for hydro first?

**Pull request merged**
